### ISSUE TITLE
Autoloader name mismatch

### ISSUE THREAD

**Issue by jlayt** [mauro-moreno/silex-jsonapi#9]
Hi,

I'm getting the following error from the autoloader:

`Case mismatch between class and real file names: JsonApiServiceProvider.php vs JSONApiServiceProvider.php in vendor/mauro-moreno/silex-jsonapi/src/`

Basically the class is named JsonApiServiceProvider but the file is named JSONApiServiceProvider.

**Comment by mauro-moreno** [comment]
Yep, I knew about the error but I didn't solve it hahaha, give me a couple of minutes and I solve it

**Comment by mauro-moreno** [comment]
There you go.

**Comment by jlayt** [comment]
Thanks!
